# Generated by Django 4.2.6 on 2024-03-12 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('contact_number', models.CharField(default='123-456-7890', max_length=20)),
                ('email', models.EmailField(default='john.doe@example.com', max_length=254)),
                ('flat_number', models.CharField(default='A101', max_length=20, null=True)),
                ('skills_interests', models.CharField(default='People Management', max_length=200)),
                ('previous_experience', models.CharField(default='Organizer', max_length=200)),
                ('availability_period', models.CharField(choices=[('One-time', 'One-time'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Always', 'Always')], default='One-time', max_length=20)),
                ('volunteer_role', models.CharField(choices=[('Administrative Assistant', 'Administrative Assistant'), ('Fundraiser', 'Fundraiser'), ('Marketing Coordinator', 'Marketing Coordinator'), ('Social Media Manager', 'Social Media Manager'), ('Event Planner', 'Event Planner'), ('Mentor', 'Mentor'), ('Food Distribution Coordinator', 'Food Distribution Coordinator'), ('Event Photographer', 'Event Photographer'), ('Event Videographer', 'Event Videographer'), ('Technical Support', 'Technical Support'), ('Inventory Manager', 'Inventory Manager'), ('Security Officer', 'Security Officer'), ('First Aid Provider', 'First Aid Provider'), ('Referee', 'Referee')], default='Administrative Assistant', max_length=100)),
                ('emergency_contact', models.CharField(default='123-456-7890', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('organiser', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('total_tickets', models.IntegerField()),
                ('price_per_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(default='Fun Activites Followed by Dinner, Bring Your Friends and Family along!', max_length=250, null=True)),
                ('free_ticket', models.BooleanField(default=False)),
                ('vendors', models.ManyToManyField(to='evmapp.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tickets', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('flat_number', models.CharField(max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(default='000', max_length=100)),
                ('ticket_id', models.CharField(editable=False, max_length=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evmapp.event')),
            ],
        ),
    ]
