# Generated by Django 4.2.6 on 2024-03-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0002_alter_booking_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='free_ticket',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
