# Generated by Django 4.2.6 on 2024-02-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0003_remove_payment_status_booking_order_id_payment_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
