# Generated by Django 4.2.6 on 2024-02-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0004_userprofile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
