# Generated by Django 5.0.2 on 2024-02-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0005_remove_userprofile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
